### ISSUE TITLE
剧本运行卡住

### ISSUE THREAD

**Issue by xiaochao** [w5teams/w5#11]
![image](https://user-images.githubusercontent.com/1953662/112796896-334ece80-909d-11eb-8757-fef1ee7ffbc7.png)
![image](https://user-images.githubusercontent.com/1953662/112796940-43ff4480-909d-11eb-9ecd-3c92d5721a88.png)
![image](https://user-images.githubusercontent.com/1953662/112796999-5aa59b80-909d-11eb-8014-975193dae079.png)

**Comment by sanjinhub** [comment]
长连接断开了，查下服务端是否启动

**Comment by rym4n** [comment]
遇到类似问题

剧本运行卡住：
![image](https://user-images.githubusercontent.com/2727351/112917661-b6236800-9135-11eb-9b80-867da7b52a68.png)

error.log：
`INFO     | core.view:after_request:57 - GET /echo  404 0 b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'`

**Comment by xiaochao** [comment]
> 长连接断开了，查下服务端是否启动

服务端正常启动，只有点开始运行，才会出现websocket close错误。
![image](https://user-images.githubusercontent.com/1953662/112921272-0a7e1600-913d-11eb-9eec-378611709641.png)

**Comment by sanjinhub** [comment]
@xiaochao 重启服务也不行吗？

**Comment by xiaochao** [comment]
> @xiaochao 重启服务也不行吗？

不行

**Comment by intediligent** [comment]
![image](https://user-images.githubusercontent.com/3184301/112932342-4e2e4b00-9150-11eb-9b02-fc612a8e0364.png)
![image](https://user-images.githubusercontent.com/3184301/112932411-6e5e0a00-9150-11eb-9ef8-ce843815c29c.png)

**Comment by sanjinhub** [comment]
@intediligent 你的代码是旧的，这个BUG昨天晚上已经修复了

**Comment by xiaochao** [comment]
这个问题是由于ES连接异常导致的，程序没有正确处理异常，导致前端页面获取不到结果，所以一直卡住 @sanjinhub
