### ISSUE TITLE
Win10+Docker Desktop 方式部署 无法访问页面

### ISSUE THREAD

**Issue by alei76** [w5teams/w5#17]
![image](https://user-images.githubusercontent.com/6091534/115688778-089b2180-a38e-11eb-8617-74af2332d3d0.png)
环境：win10 、Docker Desktop、数据库外置
启动命令：docker run -t --rm --name W5_SOAR -p 8888:8888 -e MYSQL_HOST="127.0.0.1" -e MYSQL_DATABASE="w5_db" -e MYSQL_USER="root" -e MYSQL_PASSWORD="root" -e MYSQL_PORT="3306"  w5team/w5:latest  /root/start
现象：网页无法打开

**Comment by sanjinhub** [comment]
数据库外置？没有使用 DOCKER , 那请使用文档最上面的命令。

**Comment by alei76** [comment]
thk
