### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lsq-connect** [w5teams/w5#21]
python3 run.py后，产生如下报错
“TypeError: required field "type_ignores" missing from Module”
python版本为3.8.2
![image](https://user-images.githubusercontent.com/53843638/117935664-896a8f00-b336-11eb-9f9a-bfc404f0b9ac.png)

**Comment by sanjinhub** [comment]
依赖库安装的版本不对吧？

**Comment by lsq-connect** [comment]
> 依赖库安装的版本不对吧？

诶？我都是直接pip install的呀；我再去试一试，谢谢大佬

**Comment by lsq-connect** [comment]
> 依赖库安装的版本不对吧？

![image](https://user-images.githubusercontent.com/53843638/117961971-4b2e9900-b351-11eb-8f7e-01c148e1a421.png)
不行，我用“virtualenv”纯净环境pip之后，会产生入行报错；提示版本冲突不兼容
