### ISSUE TITLE
mac 上搭建开发环境出现错误

### ISSUE THREAD

**Issue by superoo1** [w5teams/w5#3]
![image](https://user-images.githubusercontent.com/29897282/102706634-a8f11480-42ce-11eb-988d-fb5df056e6bb.png)

**Comment by sanjinhub** [comment]
Pythom 什么版本？必须是 3.8.2

**Comment by superoo1** [comment]
3.7 ，我更换下

**Comment by superoo1** [comment]
3.8 已经解决
