### ISSUE TITLE
调用webhook过快会导致重复任务

### ISSUE THREAD

**Issue by rym4n** [w5teams/w5#34]
因为 Auto 类的 run 每次会从数据库读取 controller_data 作为参数再执行，如果剧本本身的执行时间较长，而调用webhook的频率较高，则会导致 auto_execute 时快速 update controller_data ，当异步任务执行时再从数据库读到的  controller_data 则会出现重复。

**Comment by sanjinhub** [comment]
收到，新版本我会修复
