### ISSUE TITLE
config.ini   特殊符号 解析出错

### ISSUE THREAD

**Issue by superoo1** [w5teams/w5#4]
![image](https://user-images.githubusercontent.com/29897282/102709453-c2518b00-42e5-11eb-8225-54b04d643b37.png)

mysql 密码 带% 解析出错

**Comment by superoo1** [comment]
解决方法，用rawconfigparser
![image](https://user-images.githubusercontent.com/29897282/102709466-f036cf80-42e5-11eb-9895-b1a456012c9c.png)

**Comment by sanjinhub** [comment]
收到，下个版本会解决。
