### ISSUE TITLE
用户名为中文时前端报错

### ISSUE THREAD

**Issue by rym4n** [w5teams/w5#41]
当 nick_name 为中文时，登陆后前端会报错：

TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

此时页面无法正确渲染，功能不可用。

**Comment by sanjinhub** [comment]
收到，我排查下

**Comment by sanjinhub** [comment]
@rym4n 已经修复，请更新下代码。
