### ISSUE TITLE
升级后老剧本中的APP无法编辑

### ISSUE THREAD

**Issue by rym4n** [w5teams/w5#42]
升级到 v0.5.1 的时候出现了一次，于是把原本所有的剧本删了重新写

今天升级到 v0.5.2 的时候又出现了，心态有点儿崩

右键点击APP进行编辑的时候，控制台报错如下：

![image](https://user-images.githubusercontent.com/2727351/146710357-a0715975-1af3-4f63-8197-96c777443d7a.png)

**Comment by sanjinhub** [comment]
新版本，需要更新SQL https://github.com/w5teams/w5/releases/tag/v0.5.2。
更新会，你再试试。

**Comment by sanjinhub** [comment]
因为新增字段不能为null, 请执行 update `w5_workflow` set if_list="",audit_list="";  进行修复
