### ISSUE TITLE
升级新版本后剧本无法导入问题

### ISSUE THREAD

**Issue by wdjcy** [w5teams/w5#44]
目前5.0新版本升级较为频繁，但是有个问题是升级后旧版本剧本无法导入，一直提示“非法格式,请检查是否为 W5 SOAR 专用 JSON 文件”，麻烦看下咋解决，不然每次升级后剧本都需要重建。。

**Comment by sanjinhub** [comment]
如果需要导入，可能需要修改json增加两个字段才可以。
建议直接在原来的基础上进行升级，不要进行迁移。
我们这边研发后续会做好兼容问题。
